[book]
authors = ["Adrien Champion <adrien.champion@email.com>"]
multilingual = false
src = "src"
title = "Blog"

[output.html]
default-theme = "navy"

[output.linkcheck]
follow-web-links = true
traverse-parent-directories = true
exclude = [ "ocamlpro\\.com" ]